name: LimitedCreative
version: '${version}'
main: io.github.fisher2911.limitedcreative.LimitedCreative
api-version: 1.17
authors: [MasterOfTheFish]
website: www.masterofthefish.com
depend:
  - FishCore
  - Vault
permissions:
  limitedcreative.active:
    description: Permission that shows if a player is in limited creative
    default: false
  limitedcreative.use:
    description: Permission to allow players to use limited creative
    default: op
  limitedcreative.cmd.change.others.mode:
    description: Permission to allow setting of other players gamemode
    default: op
  limitedcreative.cmd.reload:
    description: Permission to reload plugin messages
    default: op
  limitedcreative.join.bypass:
    description: Permission to bypass setting to creative on join
    default: op